# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherByMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=8)),
                ('city_name', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=12)),
                ('weather_str', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='weatherbymonth',
            unique_together=set([('city_code', 'month')]),
        ),
    ]
